version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:7.2
    restart: always
    ports:
      - "6389:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis_network

volumes:
  redis_data:

networks:
  redis_network:
