version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - "6389:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - redis_network

volumes:
  redis_data:

networks:
  redis_network:
